version: "3.3"

services:
  osmosis:
    profiles: [tools]
    build:
      context: docker/osmosis
    environment:
      DATABASE_URL: postgresql://postgres@postgres:5432/postgres
    volumes:
      - ../../data:/data
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:15-3.4
    shm_size: 1g
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    extends:
      file: ../../docker-compose-base.yaml
      service: api
    environment:
      BACKEND: PostgresOsmosis
      DATABASE_URL: postgresql://postgres@postgres:5432/postgres
    volumes:
      - .:/srv/app/backends/postgres_osmosis
    depends_on:
      - postgres

volumes:
  pgdata:
