name: Test Ruby

on:
  push:
    branches: [ master, dev ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master, dev ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gh-pages-wasm:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    permissions:
      contents: write

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Rust âš™ï¸
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install and Build ğŸ”§
        env:
          VITE_PARQUET_URL: ${{ vars.VITE_PARQUET_URL }}
        run: |
          cd underpass-wasm &&
          yarn install &&
          yarn build

      - run: rm -fr .git/hooks/*
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: underpass-wasm/dist

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: [test]
  #   if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || startsWith(github.event.ref, 'refs/tags/v')

  #   permissions:
  #     contents: read
  #     packages: write
  #     id-token: write

  #   steps:
  #     - name: Docker Build and Push
  #       uses: cartoway/docker-compose-build-push-action@main
  #       with:
  #         registry_password: ${{ secrets.GITHUB_TOKEN }}
  #         project: teritorio/underpass-api
  #         service: api
